### ISSUE TITLE
Support for browsers without local storage?

### ISSUE THREAD

**Issue by saz** [roombelt/roombelt#20]
We're running some screens with a raspberry pi and uzbl-core as browser.
If we're showing a dashboard on those systems, after every restart we have to reconnect each device within the roombelt admin interface (they're showing a new code after restart).

As far as I can see, this is due to the fact, that uzbl-core is somewhat limited in support of local storage.

Is there any other way of registering such devices (e.g. a device-specific URL) or maybe support cookie/session based storage?

**Comment by ziolko** [comment]
In fact, Roombelt uses cookies to store a session key. I'm configuring an environment with `uzbl-core` and will try to reproduce this issue. 

You wrote: "If we're showing a dashboard on those systems, after every restart we have to reconnect each device". Do you mean page refresh, browser restart or the device restart?

**Comment by ziolko** [comment]
@saz, I've just run the `uzbl-core` and on my environment it persists session between restarts so it's probably some configuration issue. 

Could you run `cat ~/.local/share/uzbl/cookies.txt` and see if there's an entry for `HttpOnly_app.roombelt.com` (please don't paste it here, because it contains your session id)?

I've just learned about `uzbl` from you, but I will do my bests to help :)

**Comment by ziolko** [comment]
@saz were you able to investigate this issue further?

**Comment by saz** [comment]
Not yet. I'll get to it tomorrow and see if I'm able to give you more details.

**Comment by saz** [comment]
Looks like as if there is in fact a problem with cookies on my systems... I'll close this issue therefore
